In [13]:
import numpy as np
import pandas as pd

In [14]:
array = np.random.randint(1, 21, size=(4, 4))
print("Question 1")
print("Part A:")
print(array)
array[array > 10] = 10
print("Part C:")
print(array)
row_sums = array.sum(axis=1)
print("Part D:")
print(row_sums)

Question 1
Part A:
[[19 10  6  1]
 [ 2 13 15  9]
 [14  5 11  8]
 [19 20 19 13]]
Part C:
[[10 10  6  1]
 [ 2 10 10  9]
 [10  5 10  8]
 [10 10 10 10]]
Part D:
[27 31 33 40]


In [15]:
data2 = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print("Question 2\nPart A:")
variance = np.var(data2)
std_dev = np.std(data2)
print("Variance:", variance)
print("Standard Deviation:", std_dev)
print("Part B:")
median = np.median(data2)
percentile_25 = np.percentile(data2, 25)
print("Median:", median)
print("25th Percentile:", percentile_25)
print("Part C:")
normalized_data = (data2 - np.mean(data2)) / np.std(data2)
print("Normalized Data:", normalized_data)

Question 2
Part A:
Variance: 131.25
Standard Deviation: 11.4564392373896
Part B:
Median: 22.5
25th Percentile: 13.75
Part C:
Normalized Data: [-1.52752523 -1.09108945 -0.65465367 -0.21821789  0.21821789  0.65465367
  1.09108945  1.52752523]


In [16]:
print("Question 3\n")
arr3 = np.arange(1, 16)
print("Part A:", arr3)
B_3 = arr3[arr3 % 2 == 0]
print("Part B:", B_3)
modified_arr3 = np.where(arr3 % 3 == 0, -3, arr3)
print("Part C:", modified_arr3)

Question 3

Part A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Part B: [ 2  4  6  8 10 12 14]
Part C: [ 1  2 -3  4  5 -3  7  8 -3 10 11 -3 13 14 -3]


In [17]:
print("Question 4\n")
x4 = np.array([1, 2, 3])
y4 = np.array([4, 5, 6])
print("Part 1:", x4, y4)
vertical_stack = np.vstack((x4, y4))

horizontal_stack = np.hstack((x4, y4))
print("Part B:\n",vertical_stack,"\n", horizontal_stack)

concatenated = np.concatenate((x4, y4))
print("Part C:", concatenated)

Question 4

Part 1: [1 2 3] [4 5 6]
Part B:
 [[1 2 3]
 [4 5 6]] 
 [1 2 3 4 5 6]
Part C: [1 2 3 4 5 6]


In [21]:
data5 = {'a': 10, 'b': 20, 'c': 30, 'd': 40}
series5 = pd.Series(data5)
print("Part A:\n", series5)
series_multiplied = series5 * 2
print("\nPart B:\n", series_multiplied)
index_exists = 'e' in series5.index
print("\nPart C:", index_exists)
df = series5.to_frame(name='Numbers')
print("\nPart D:\n", df)

Part A:
 a    10
b    20
c    30
d    40
dtype: int64

Part B:
 a    20
b    40
c    60
d    80
dtype: int64

Part C: False

Part D:
    Numbers
a       10
b       20
c       30
d       40


In [23]:
df = pd.DataFrame({
    'A': np.random.randint(0, 51, size=5),
    'B': np.random.randint(0, 51, size=5),
    'C': np.random.randint(0, 51, size=5)
})
print("Part A:\n", df)
df['D'] = df['A'] + df['B']
print("\nPart B:\n", df) 
df = df.drop(columns=['C'])
print("\nPart C:\n", df)
df = df.rename(columns={'D': 'Total'})
print("\nPart D:\n", df) 

Part A:
     A   B   C
0  11  22   9
1  20  37  43
2  16  35  37
3  22  25  31
4  36  13  13

Part B:
     A   B   C   D
0  11  22   9  33
1  20  37  43  57
2  16  35  37  51
3  22  25  31  47
4  36  13  13  49

Part C:
     A   B   D
0  11  22  33
1  20  37  57
2  16  35  51
3  22  25  47
4  36  13  49

Part D:
     A   B  Total
0  11  22     33
1  20  37     57
2  16  35     51
3  22  25     47
4  36  13     49


In [26]:
today = pd.to_datetime('today')
date_index = pd.date_range(today, periods=len(df), freq='D')
df.index = date_index
print("Part A:\n", df)
filtered_df = df[df['Total'] > 50]
print("Part B:\n", filtered_df)

# c) Select only the 'A' and 'Total' columns for the first three rows
selected_columns_rows = df[['A', 'Total']].iloc[:3]
print("\nPart C:\n", selected_columns_rows)

Part A:
                              A   B  Total
2024-11-09 08:14:25.137649  11  22     33
2024-11-10 08:14:25.137649  20  37     57
2024-11-11 08:14:25.137649  16  35     51
2024-11-12 08:14:25.137649  22  25     47
2024-11-13 08:14:25.137649  36  13     49
Part B:
                              A   B  Total
2024-11-10 08:14:25.137649  20  37     57
2024-11-11 08:14:25.137649  16  35     51

Part C:
                              A  Total
2024-11-09 08:14:25.137649  11     33
2024-11-10 08:14:25.137649  20     57
2024-11-11 08:14:25.137649  16     51


In [28]:
data = {'Name': ['Tom', 'James', 'Ricky', 'Vin', 'Steve'],
        'Age': [28, 34, np.nan, 29, np.nan],
        'Score': [85.0, np.nan, 79.0, np.nan, 92.0]}
df = pd.DataFrame(data)

print("Part A:\n", df)
missing_columns = df.columns[df.isnull().any()]
print("\nPart B:", missing_columns)
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)
print("Part C:\n", df)
df = df.dropna(subset=['Score'])
print("\nPart D:\n", df)

Part A:
     Name   Age  Score
0    Tom  28.0   85.0
1  James  34.0    NaN
2  Ricky   NaN   79.0
3    Vin  29.0    NaN
4  Steve   NaN   92.0

Part B: Index(['Age', 'Score'], dtype='object')
Part C:
     Name   Age  Score
0    Tom  28.0   85.0
1  James  34.0    NaN
2  Ricky  29.0   79.0
3    Vin  29.0    NaN
4  Steve  29.0   92.0

Part D:
     Name   Age  Score
0    Tom  28.0   85.0
2  Ricky  29.0   79.0
4  Steve  29.0   92.0


In [30]:
data = {'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
        'Player': ['John', 'Alice', 'Bob', 'Emily', 'Frank', 'Grace'],
        'Points': [10, 15, 20, 25, 30, 35]}
df = pd.DataFrame(data)
team_points = df.groupby('Team')['Points'].sum().reset_index()
print("Part A:\n", team_points)
max_points_player = df.loc[df.groupby('Team')['Points'].idxmax()][['Team', 'Player', 'Points']]
print("\nPart B:\n", max_points_player)

Part A:
   Team  Points
0    A      25
1    B      45
2    C      65

Part B:
   Team Player  Points
1    A  Alice      15
3    B  Emily      25
5    C  Grace      35


In [31]:
data = {'Name': ['Anna', 'Ben', 'Charlie', 'Diana', 'Ethan', 'Fiona'],
        'Age': [28, 22, 35, 30, 40, 25],
        'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Chicago', 'Los Angeles'],
        'Income': [50000, 60000, 75000, 82000, 90000, 45000]}

df = pd.DataFrame(data)

age_filtered = df[df['Age'] > 30]
print("Part A:\n", age_filtered)
city_filtered = age_filtered[age_filtered['City'].isin(['New York', 'Chicago'])]
print("Part B:\n", city_filtered)
average_income = city_filtered['Income'].mean()
print("\nPart C:", average_income)
reset_index_df = city_filtered.reset_index(drop=True)
print("\nPart D:\n", reset_index_df)

Part A:
       Name  Age      City  Income
2  Charlie   35  New York   75000
4    Ethan   40   Chicago   90000
Part B:
       Name  Age      City  Income
2  Charlie   35  New York   75000
4    Ethan   40   Chicago   90000

Part C: 82500.0

Part D:
       Name  Age      City  Income
0  Charlie   35  New York   75000
1    Ethan   40   Chicago   90000
